### ISSUE TITLE
Ajout du workflow CRUD de projet

### ISSUE THREAD

**Issue by nlarche** [L-J-N/site#3]
Page accessible en admin
- Liste des projets (tri, filtre, suppression)
- Page de création / modification

Définir les champs d'un projet à afficher dans la liste
Définir les champs lors de la création
Définir les champs modifiable

**Comment by nlarche** [comment]
@Jabuf à ton avis on fait uniquement des suppressions logique ?

**Comment by Jabuf** [comment]
Ça dépend, l'intérêt des suppressions logiques c'est d'éviter toute la merde avec les entités liées.
Dans notre cas on aura deux entités principales, projet et utilisateur, je pense que pour cela la suppression logique est fortement recommandée. Après pour des entités assez indépendantes (pas d'exemple en tête) on peut supprimer direct, enfin tu vois l'idée.

**Comment by Jabuf** [comment]
Pour les champs tu peux regarder ici et ici : 

https://github.com/L-J-N/site/wiki/Projet-liste-bloc-projet
https://github.com/L-J-N/site/wiki/Projet-attributs
